package com.example.backent.entity.enums;

public enum RoleName {
  USER, //
  SUPER_ADMIN, // ALL
  DIRECTOR, // DASHBOARD
  PM, // PROJECTS COMPANY DEVELOPER
  DEV, // SEE PROJECT WORKING PROJECT
  BA, // TZ GENERATION CREATE INACTIVE PROJECT
  QUE, // WORK IN PROJECT QUE BOARD
}
